apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-long-running-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-long-running
  template:
    metadata:
      labels:
        app: be-long-running
    spec:
      containers:
      - name: be-long-running-container
        image: rookie7722/be_long_running:v4_mac   # <-- replace with your Docker Hub image
        envFrom: 
          - configMapRef:
              name: env-config
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 500m
          limits: 
            cpu: 1000m
---

# now we need to create something like a nodeport
apiVersion: v1
kind: Service
metadata:
  name: be-long-running-service
spec:
  type: NodePort
  selector:
    app: be-long-running
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008
